### PR TITLE
[TC-5330] Add supported media types and file extensions

### PR DESCRIPTION
**Pull request by marcmatt**
## Description

https://tradecloud.atlassian.net/browse/TC-5330

### Scope
This PR adds supported media types and file extensions
according to object-storage/src/main/scala/com/tradecloud1/objectstorage/api/FilesValidator.scala

https://tradecloud.gitbook.io/api/v/TC-5330-supported-media-types/security/media-types

### Submitter pre-flight check

- [ ] Review your documentation
- [ ] Add labels `needs reviewing`
- [ ] Assign PR and JIRA ticket to 'Reviewer' (in 'Reviewing' state)

### Reviewer pre-flight check

- [ ] Review documentation in PR
- [ ] Remove label `needs reviewing`
- [ ] Merge the PR and remove the release for this branch from Gitbook
- [ ] Set Jira ticket to 'Released'

### CODE REVIEW

**Review by Sjorstradecloud — APPROVED** [review]
Looks good for as far I can judge. Please inform me when I can share the page/list with GAC.

**Review by olegtradecloud — APPROVED** [review]
Looks good!

**Comment by marcmatt** [comment]
@Sjorstradecloud The media types list is available here: https://tradecloud.gitbook.io/api/security/media-types

**Comment by Sjorstradecloud** [comment]
@marcmatt , Thanks! Will share it with GAC.

**Pull request merged**
