### PR TITLE
[TC-8660] Fix URL paths

### PR DESCRIPTION
**Pull request by marcmatt**
## Description

https://tradecloud.atlassian.net/browse/TC-8660

### Scope
This PR fixes by Gitbook generated URL paths, useful for bookmarking.

Example
image

### Submitter pre-flight check

- [ ] Review your documentation
- [ ] Add labels `needs reviewing`
- [ ] Assign PR and JIRA ticket to 'Reviewer' (in 'Reviewing' state)

### Reviewer pre-flight check

- [ ] Review documentation in PR
- [ ] Remove label `needs reviewing`
- [ ] Merge the PR and remove the release for this branch from Gitbook
- [ ] Set Jira ticket to 'Released'

### CODE REVIEW

**Comment by marcmatt** [comment]
@roy-tc @Sjorstradecloud Please review https://app.gitbook.com/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/UdXCx0pyRKjxuwakMDOE/

**Comment by Sjorstradecloud** [comment]
@marcmatt we want them to be like "/api/order/process/receive"? 
If so, then it is OK, tested via the public API manual.

**Comment by marcmatt** [comment]
@Sjorstradecloud You have to test https://app.gitbook.com/s/-LNyJ9UuwLCjTvA2sqQR-887967055/~/revisions/UdXCx0pyRKjxuwakMDOE/
image

**Review by roy-tc — APPROVED** [review]

**Review by Sjorstradecloud — APPROVED** [review]
Clear, thanks. 
URL end's look good

**Pull request merged**
